### ISSUE TITLE
possible typo in second post

### ISSUE THREAD

**Issue by 0xYYY** [kcking/implfuture.dev#1]
first of all, great post! didn't know it's already this viable to create a full-stack rust website now

noticed a possible typo when reading the second post, should `BlogIndex` be `BlogPost` instead here?
https://github.com/kcking/implfuture.dev/blob/91db72da5cc95ef50256b61ba1ab677d185a1091/src/blog/post2.mdx?plain=1#L119-L122

**Comment by kcking** [comment]
Thanks! Also good catch, fixed in b6f31159ffdaabf108e1bad5f353e561febb14ea
